apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: retail-store
  source:
    repoURL: https://github.com/iemafzalhassan/retail-store-sample-app
    targetRevision: main
    path: src/app
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: global.imageRegistry
          value: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-store
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 